### ISSUE TITLE
[FEATURE] Agregar link a próximo concurso al que está registrado un usuario en la página principal

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#6910]
Como usuario  difícil encontrar el link al concurso al que estás registrado sobre todo para estudiantes que no tienen experiencia en la plataforma.

Agregar link e información básica sobre el siguiente concurso al que estás registrado. 

![image](https://user-images.githubusercontent.com/940007/221051504-99dffe56-4e04-4bba-b754-96c1ac01c6b7.png)

**Comment by mohammadshaad** [comment]
Can I work on this issue if it is not assigned to anyone?

**Comment by devbrianmedina** [comment]
I have finished the four problems of the GSoC test, I would like to work on this. My omegaup username is DevBrianMedina.

**Comment by heduenas** [comment]
@mohammadshaad have completed the programming test at https://omegaup.com/arena/gsoc2023 ?
Completing at least 3 problems is a prerequisite to getting an issue assigned.

Assigning this issue to @devbrianmedina since I don't see @mohammadshaad in the omegaup test.

**Comment by devbrianmedina** [comment]
@heduenas Could you change my assignment for this #6939

**Comment by heduenas** [comment]
> @heduenas Could you change my assignment for this #6939

Done

**Comment by satishsahu25** [comment]
is this issue open?

**Comment by heduenas** [comment]
@satishsahu25 this issue is open, but is being worked on by @devbrianmedina. Please look for another one.

**Comment by pabo99** [comment]
It seems @devbrianmedina is working on  #6950, so this issue is still available

**Comment by EmanuelJLL** [comment]
Can you please assign me this issue?
I have already solved 3 of the 4 problems in the second contest of phase 1, my username is EmanuelJ

**Comment by heduenas** [comment]
Assigned to @EmanuelJLL

**Comment by rafa238** [comment]
I've seen this issue is still open, can you assign me this issue?
